package org.egov.bpa.web.model.NOC;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum NocType {

	CIVIL_AVIATION("CIVIL_AVIATION"), ARCHAEOLOGY("ARCHAEOLOGY"), STRUCTURAL_SAFETY("STRUCTURAL_SAFETY"),
	SOIL_TEST("SOIL_TEST"), POLICE_CLEARANCE("POLICE_CLEARANCE"), ENVIRONMENT("ENVIRONMENT"),
	ELECTRICITY_DEPT("ELECTRICITY_DEPT"), SAD_CLEARANCE("SAD_CLEARANCE"), HOME_SECURITY("HOME_SECURITY"),
	CIVIL_AVIATION_AZARA("CIVIL_AVIATION_AZARA"), AZARA_CIRCLE("AZARA_CIRCLE"), WATER_RESOURCES("WATER_RESOURCES"),
	FIRE_SAFETY("FIRE_SAFETY"), POLLUTION_CONTROL("POLLUTION_CONTROL"), ARMY_DEFENCE("ARMY_DEFENCE"),
	GROUND_WATER("GROUND_WATER"), HEALTH_AUTHORITY("HEALTH_AUTHORITY"), SACFA_RF("SACFA_RF"),
	ELECTRICAL_INSPECTOR("ELECTRICAL_INSPECTOR"), LIFT_SAFETY("LIFT_SAFETY"), STP_CLEARANCE("STP_CLEARANCE"),
	ESZ_CLEARANCE("ESZ_CLEARANCE");

	private final String value;

	@Override
	@JsonValue
	public String toString() {
		return this.value;
	}
}
